schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "VpcEnvironmentInput"

  types:
    VpcEnvironmentInput:
      type: object
      description: "Input properties for a vpc environment."
      properties:
        az:
          type: string
          description: "The single az"
          minLength: 1
          maxLength: 10
        vpc_name:
          type: string
          description: "Name for vpc"
